import { Job } from "@/lib/types";

export const mockJobs: Job[] = [
  {
    id: "gh-stripe-senior-backend",
    title: "Senior Backend Engineer",
    company: "Stripe",
    location: "Remote (US)",
    isRemote: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    isNew: true,
    stack: ["node.js"],
    seniorities: ["senior"],
  },
  {
    id: "ashby-notion-frontend",
    title: "Frontend Engineer",
    company: "Notion",
    location: "Remote (EU)",
    isRemote: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    isNew: true,
    stack: ["node.js"],
    seniorities: ["mid"],
  },
  {
    id: "gh-vercel-devops",
    title: "DevOps Engineer",
    company: "Vercel",
    location: "San Francisco, US",
    isRemote: false,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    isNew: false,
    stack: ["golang"],
    seniorities: ["senior"],
  },
  {
    id: "ashby-linear-backend",
    title: "Backend Engineer",
    company: "Linear",
    location: "Remote",
    isRemote: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    isNew: false,
    stack: ["node.js", "python"],
    seniorities: ["mid"],
  },
  {
    id: "gh-github-qa",
    title: "QA Automation Engineer",
    company: "GitHub",
    location: "Remote (US)",
    isRemote: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    isNew: false,
    stack: ["python"],
    seniorities: ["mid"],
  },
  {
    id: "ashby-ramp-fullstack",
    title: "Staff Fullstack Engineer",
    company: "Ramp",
    location: "New York, US",
    isRemote: false,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    isNew: false,
    stack: ["node.js"],
    seniorities: ["staff"],
  },
];
